model:
  DEMUCS:
    chin: 1
    chout: 1
    hidden: 48
    max_hidden: 10000
    causal: true
    glu: true
    depth: 5
    kernel_size: 8
    stride: 4
    normalize: true
    resample: 4
    growth: 2
    rescale: 0.1

  LSTM:
    num_layers: 2
    hidden_size: 257
    bidirectional: False
    feat:
      win_len: 512
      hop_len: 256
      n_freq: 257
      log: True

  GRU:
    num_layers: 2
    hidden_size: 257
    bidirectional: False
    feat:
      win_len: 512
      hop_len: 256
      n_freq: 257
      log: True

stftloss:
  factor_sc: 0.5
  factor_mag: 0.5
  
optimizer: 
  SGD:
    lr: 0.03
    momentum: 0.9
    weight_decay: 1.0e-4
  Adam:
    lr: 0.0002                                 
    betas: !!python/tuple [0.9, 0.999]
  
train:
  gradient_clipping: 1.0 
  batch_size: 8                                         # training batch size
  acml_batch_size: 8                                    # training batch size
  total_steps: 500000                                   # total steps for training, a step is a batch of update
  eval_step: 20000                                      # save model every this amount of training steps
  log_step: 100                                         # save model every this amount of training steps
  max_length: 80000
  min_length: 24000
  Corruptor:
    snrs: [0, 3, 6, 9, 12]
    duplicate: True

eval:
  metrics: ['sisdr', 'stoi', 'pesq_nb', 'pesq_wb']
  Corruptor:
    snrs: [0, 3, 6, 9, 12]
    duplicate: True

dataset:
  train:
    speech: ../speech_data/LibriSpeech/train-clean-360
    noise: ../noise_data/DNS_noise
  dev:
    speech: ../speech_data/LibriSpeech/dev-clean
  test:
    data: ../NASTAR_VCB_test_data
 